{
 "title": "Secrets Exporter",
 "description": "Shows certitificate expiration times, as well as failed ssl connects",
 "tags": [
  "ssl",
  "tls"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ssl_probe_success, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Unique Certificates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_kubernetes_cert_not_after{instance=~\"$instance\",job=~\"$job\"}) by (issuer_cn,serial_no))"
    }
   ]
  },
  {
   "title": "Total Probe Targets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_kubernetes_cert_not_after{instance=~\"$instance\",job=~\"$job\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Failed SSL Connects History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{job=~\"$job\", instance=~\"$instance\"} == 0 or ssl_probe_success{job=~\"$job\", instance=~\"$instance\"} == 0)^0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certificates",
   "type": "table-old",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((ssl_kubernetes_cert_not_after{instance=~\"$instance\",job=~\"$job\"} - time())/24/60/60)"
    }
   ]
  }
 ]
}