name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
# name: Release Charts

# on:
#   push:
#     branches:
#       - main

# jobs:
#   release:
#     permissions:
#       id-token: write
#       contents: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Fetch history
#         run: git fetch --prune --unshallow

#       - name: Configure Git
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#       - name: Set up Helm
#         uses: azure/setup-helm@v2.0
#         with:
#           version: v3.8.1

#       - name: Run chart-releaser
#         uses: helm/chart-releaser-action@v1.4.0
#         env:
#           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#           CR_SKIP_EXISTING: "true"

#       - name: Add dependency chart repos
#         run: |
#           helm repo add xjulio https://xjulio.github.io/helm-charts
