on:
  push:
    branches:
      - "main"
    paths:
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify README changed
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            README.md
      - name: copy README.md
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v2
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
